version: "3.3"
services:
  api:
    image: node:18-alpine
    ports:
      - "8000:80"
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongo-db
    networks:
      - backend
    command: npm run server:dev

  mongo-db:
    image: "mongo:latest"
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - ./frontend
      - ./api/build:/usr/src/app/build
    stdin_open: true
    tty: true


networks:
  backend:
    driver: bridge